# Generated by Django 5.0.1 on 2025-12-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_image_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_logos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
    ]
