# Generated by Django 5.0.1 on 2026-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_aboutsection_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'api_contactmessage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi bi-lightbulb-fill', max_length=100)),
                ('icon_color', models.CharField(default='#0099FF', max_length=50)),
                ('stat_class', models.CharField(default='base-stat-1', help_text='CSS class: base-stat-1, base-stat-2, base-stat-3', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'db_table': 'api_corevalue',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('category_tag', models.CharField(choices=[('hrms', 'HRMS'), ('crm', 'CRM'), ('pos', 'POS System'), ('erp', 'ERP Solution'), ('other', 'Other')], default='hrms', max_length=50)),
                ('icon', models.CharField(default='bi bi-people-fill', max_length=100)),
                ('icon_color', models.CharField(default='#2E7D32', max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('demo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'api_product',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi bi-code-slash', help_text='Bootstrap icon class e.g. bi bi-code-slash', max_length=100)),
                ('icon_color', models.CharField(default='#0d6efd', help_text='HEX or color class e.g. #0d6efd', max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'api_service',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Motion Tech Ltd', max_length=150)),
                ('site_title', models.CharField(default='Motion Tech Ltd - Software Development & IT Solutions', max_length=255)),
                ('tagline', models.CharField(default='Crafting Digital Solutions That Businesses Trust', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('email', models.CharField(default='info@jatrasoft.com', max_length=150)),
                ('phone', models.CharField(default='+8801601693138', max_length=50)),
                ('address', models.CharField(default='123 Main Street, Dhaka, Bangladesh', max_length=255)),
                ('whatsapp_number', models.CharField(default='8801601693138', max_length=50)),
                ('calendly_url', models.CharField(default='https://calendly.com/hafizul-islam/30min', max_length=500)),
                ('facebook_url', models.CharField(blank=True, default='https://facebook.com', max_length=500, null=True)),
                ('twitter_url', models.CharField(blank=True, default='https://twitter.com', max_length=500, null=True)),
                ('instagram_url', models.CharField(blank=True, default='https://instagram.com', max_length=500, null=True)),
                ('linkedin_url', models.CharField(blank=True, default='https://linkedin.com', max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('footer_about', models.TextField(blank=True, default='Our mission is to deliver high-quality software solutions that empower businesses and individuals to achieve more with technology.', null=True)),
                ('copyright_text', models.CharField(default='Motion Tech Ltd. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'api_sitesetting',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=255)),
                ('icon', models.CharField(default='bi bi-laptop', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology Stack',
                'verbose_name_plural': 'Technology Stacks',
                'db_table': 'api_techstack',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi bi-laptop', max_length=100)),
                ('icon_color', models.CharField(default='text-primary', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us',
                'verbose_name_plural': 'Why Choose Us',
                'db_table': 'api_whychooseus',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='journey_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='journey_subtitle',
            field=models.CharField(default='OUR JOURNEY SO FAR', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='journey_title',
            field=models.CharField(default='Building the Digital Future with Motion Tech', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='stat_clients',
            field=models.CharField(default='50+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='stat_experience',
            field=models.CharField(default='4+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='stat_projects',
            field=models.CharField(default='100+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title',
            field=models.CharField(default='Our Vision', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='clients_stat',
            field=models.CharField(default='50+ Clients', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='experience_stat',
            field=models.CharField(default='4+ Years', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_btn_text',
            field=models.CharField(default='Get Started', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_btn_url',
            field=models.CharField(default='/services/', max_length=255),
        ),
        migrations.AddField(
            model_name='herosection',
            name='projects_stat',
            field=models.CharField(default='100+ Projects', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_btn_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_btn_url',
            field=models.CharField(default='/contact/', max_length=255),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
