# Generated by Django 5.0.1 on 2026-09-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactmessage_corevalue_product_service_sitesetting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['id'], 'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['id'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['id'], 'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
